version: '3.8'

services:
  db:
    image: bitnami/postgresql:17
    container_name: db
    environment:
      POSTGRES_DB: default_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d default_db"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  api:
    build: ./backend
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:1234@db:5432/default_db
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
  
  gui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gui
    ports:
      - 80:80
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: